"""
Django settings for mysitel project.

Generated by 'django-admin startproject' using Django 2.2.13.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))#项目根路径（保存Django项目的所有文件,)
print(os.path.abspath(__file__))#settings文件的绝对路径
print(os.path.dirname(os.path.abspath(__file__)))#settings文件的所在目录
print(BASE_DIR)#settings文件的所在根路径

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'sq6+qz&27xwsd&yjv6n1jzmo1axa^*h#5c@j^mbn903_$80c4d'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True#表示Django所处在开发模式（1.修改完可及时生效 2.页面报错信息非常详细）,上线后不容许给用户看页面的报错信息

ALLOWED_HOSTS = ['127.0.0.1','172.40.54.194']#默认为两个ip地址，一个回环地址，一个localhost，目的是确认访问地址


# Application definition


#应用
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]
#中间件
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

#主路由配置（一般不修改）
ROOT_URLCONF = 'mysitel.urls'


#渲染界面（给数据穿衣服，前端），前后端分离的好处（高并发，响应快）
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

#项目部署时涉及（协议）
WSGI_APPLICATION = 'mysitel.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

#数据库
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',#嵌入式会用的小型数据库
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators


#密码输入规则
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/
#语言
LANGUAGE_CODE = 'zh-Hans'

#时区
TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'
