# Generated by Django 2.2.12 on 2020-08-20 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='书名')),
                ('pub', models.CharField(max_length=20, verbose_name='出版社')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='价格')),
            ],
        ),
    ]
