# Generated by Django 2.2.13 on 2020-08-11 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0002_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='diver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diver_name', models.CharField(max_length=10, verbose_name='司机名称')),
                ('commany_name', models.CharField(max_length=10, null=True, verbose_name='公司名称')),
            ],
        ),
    ]
